
Debug: true
# name of observ object
object: test
# on/off true/false
source_on: true
# source_on: false
recv_streams: 8 
Storage_folder: /data/
observation_mode: 1      # Must match the sender: 1=spectral line, 2=continuum
